### PR TITLE
Dynamically copy Makefile.in.in and quotation mark fix

### PR DESCRIPTION
**Pull request by mako2580**
Solving https://github.com/sabotage-linux/gettext-tiny/issues/21

### CODE REVIEW

**Comment by mako2580** [comment]
OK, So should I close this pull request and make a new one ?

**Comment by xhebox** [comment]
@mako2580 no, you could just do like so:
1. backup your work, like `git diff HEAD~2` to get a patch 
2. `git reset --hard HEAD~2`, and your commits will roll back
3. recommits, and `git push --force`

If you are interested in git, you could also playaround `git rebase -i` commands.

**Comment by xhebox** [comment]
Last check, can these commits work out your compiling?

**Comment by mako2580** [comment]
Yeah, checked again.

**Pull request merged**
