### PR TITLE
ABOUT-NLS destination fix and added Makevars.template

### PR DESCRIPTION
**Pull request by mako2580**
This is fix for bug we created in solving issue https://github.com/sabotage-linux/gettext-tiny/issues/18 and added `Makevars.template` in order to compile `bison` package

### CODE REVIEW

**Comment by rofl0r** [comment]
thanks! could you elaborate a bit on what that template is for ?

**Comment by mako2580** [comment]
Well, of course I can. `Makevars.template` is needed by `bootstrap` of `bison` package during compilation. One of the section where is needed is following

```
# Create gettext configuration.
  echo "$0: Creating po/Makevars from po/Makevars.template ..."
  rm -f po/Makevars
  sed '
    /^EXTRA_LOCALE_CATEGORIES *=/s/=.*/= '"$EXTRA_LOCALE_CATEGORIES"'/
    /^COPYRIGHT_HOLDER *=/s/=.*/= '"$COPYRIGHT_HOLDER"'/
    /^MSGID_BUGS_ADDRESS *=/s|=.*|= '"$MSGID_BUGS_ADDRESS"'|
    /^XGETTEXT_OPTIONS *=/{
      s/$/ \\/
      a\
          '"$XGETTEXT_OPTIONS"' $${end_of_xgettext_options+}
    }
  ' po/Makevars.template >po/Makevars \
    || die 'cannot generate po/Makevars'
```

I was searching where does it usually get `po/Makevars.template` from, and I find out it's part of `gettext`, so I copied it to `data` folder, and edited `autopoint.in` properly to make changes take effect. And it worked ! If you want to rename the file or edit the content of template, you can do whatever you want, I just want to merge it in most "vanilla" way as possible.

**Comment by rofl0r** [comment]
LGTM. @xhebox any thoughts ?

**Comment by xhebox** [comment]
@rofl0r If the license is OK, then it's OK. Template file is just a dump file to pass the configure, our Makefile does not depend on it at all.

**Comment by mako2580** [comment]
@xhebox Inside `Makevars,template`, on the top comment is written `This file, Makevars,template, is free software; the Free Software Foundation gives unlimited permission to use, copy, distribute, and modify it.` so I guess it's OK on license side.

**Pull request merged**
